Fix: TypeError: render2 is not a function
The application was throwing a `TypeError: render2 is not a function` error. This commit addresses the root cause of this error.